project: coconut
save_path: ./ckpts
name: gsm_coconut_simcot_eval

only_eval: True

coconut: True
cot: False
no_thoughts: False
no_cot: False
coconutgpt: True

c_thought: 2
epochs_per_stage: 3
max_latent_stage: 5
pad_latent_to_max: True

save_only_improve: False
uniform_prob: 0.0

# Model and checkpoint paths (use relative or env variables)
model_id: ./pretrained/gpt2
load_model_path: ./ckpts/gsm_coconut_simcot/checkpoint_30

wandb: False
seed: 0
resume: 3
bf16: False

# data
train_path: ./data/gsm_train.json
val_path: ./data/gsm_test.json

reset_optimizer: True
batch_size_training: 8
debug: False
gradient_accumulation_steps: 1
num_epochs: 35
lr: !!float "1e-4"
weight_decay: 0.01

w_prompt: False
mode: coconutgpt_same_word_embedding
explain_mode: v1_aug

training_method: full
train_or_eval: eval
